<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MJ9FF9G422" failures="1" tests="2" name="Default test" time="1.114" errors="0" timestamp="2023-10-17T16:25:23 SAST">
  <testcase classname="packOne.Demo1" name="firstTestCase" time="1.04">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method packOne.Demo1.firstTestCase() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method packOne.Demo1.firstTestCase() didn't finish within the time-out 1000
at java.base@17.0.2/java.lang.Thread.sleep(Native Method)
at app//packOne.Demo1.firstTestCase(Demo1.java:12)
at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.2/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.2/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.2/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.2/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.2/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- firstTestCase -->
  <testcase classname="packOne.Demo1" name="secondTestCase" time="0.001"/>
</testsuite> <!-- Default test -->
